<template>
    <div>
        <el-row type="flex" justify="center" style="width: 1700px">
            <el-col :span="6">
                <el-progress :text-inside="true" :stroke-width="24" :percentage="capacity.percentage"
                             :status="this.$options.filters.statusFilter(this.capacity.percentage)"></el-progress>
            </el-col>
            <el-col :span="4">当前系统总容量：{{capacity.allCapacity}}</el-col>
            <el-col :span="3">已用容量：{{capacity.useCapacity}}</el-col>

        </el-row>
        <el-divider content-position="left">
            <el-button-group>
                <el-button type="primary" icon="el-icon-back" size="small" :disabled="backBtnVisitable"
                           @click="handlerBackBtn"></el-button>
                <el-button type="primary" icon="el-icon-right" size="small" :disabled="rightBtnVisitable"
                           @click="handlerRightBtn"></el-button>
                <el-button type="primary" icon="el-icon-refresh-right" size="small"
                           @click="handlerRefreshBtn"></el-button>
            </el-button-group>
        </el-divider>
        <div style="margin: 0 auto;width: 1600px">
            <div v-for="(item,index) of fileList" :key="index" class="icon-div" @dblclick="openFile(item)"
                 @contextmenu.prevent.stop="rightClick(item,$event)"
                 @mouseover="mouseOver(item,$event)"
                 @mouseleave="mouseLeave(item,$event)">
                <img :src="require('../../../assets/'+item.isDirectory+'.png')" height="60" width="60" class="div-img"/>
                <el-tooltip class="item" effect="dark" :content="item.name" placement="bottom">
                    <p class="img-div-p" v-text="item.name" style="margin: 5px 0 5px 0"></p>
                </el-tooltip>
            </div>
        </div>


        <div v-show="menuVisible">
            <ul id="menu" class="menu" style="margin: 0 0 0 0;padding: 0 15px 0 15px">
                <li class="menu__item">打开</li>
                <li class="menu__item_line"></li>

                <li class="menu__item" @click="downLoadFile"
                    v-if="this.currentItem.isDirectory=='directory'?false:true">下载
                </li>
                <li class="menu__item_line" v-if="this.currentItem.isDirectory=='directory'?false:true"></li>
                <li class="menu__item">复制</li>
                <li class="menu__item_line"></li>
                <li class="menu__item">剪切</li>
                <li class="menu__item_line"></li>
                <li class="menu__item">删除</li>
                <li class="menu__item_line"></li>
                <li class="menu__item">重命名</li>
                <li class="menu__item_line"></li>
                <li class="menu__item" @click="getFileInfo">详细信息</li>
                <li class="menu__item_line"></li>
            </ul>
        </div>


        <!--文件详细信息弹框-->
        <el-dialog title="详细信息" :visible.sync="fileInfoVisible" width="400px" :before-close="handleFileInfoClose"
                   :close-on-click-modal="false">
            <el-row type="flex" justify="space-around" :gutter="30">
                <el-col :span="2"></el-col>
                <el-col :span="6"><p class="el-p">类型</p></el-col>
                <el-col :span="16"><p class="el-p" v-text="fileInfo.type"></p></el-col>
            </el-row>
            <el-row type="flex" justify="space-around" :gutter="30">
                <el-col :span="2"></el-col>
                <el-col :span="6"><p class="el-p">大小</p></el-col>
                <el-col :span="16"><p class="el-p" v-text="this.fileInfo.size"></p></el-col>
            </el-row>
            <el-row type="flex" justify="space-around" :gutter="30">
                <el-col :span="2"></el-col>
                <el-col :span="6"><p class="el-p">创建时间</p></el-col>
                <el-col :span="16"><p class="el-p" v-text="fileInfo.ctime"></p></el-col>
            </el-row>
            <el-row type="flex" justify="space-around" :gutter="30">
                <el-col :span="2"></el-col>
                <el-col :span="6"><p class="el-p">修改时间</p></el-col>
                <el-col :span="16"><p class="el-p" v-text="fileInfo.mtime"></p></el-col>
            </el-row>
        </el-dialog>

        <!--由于360浏览器下载会根据文件的大小不停的向后端发请求，导致后端数据库连接池满载和java的oom，现使用form表单解决无限次请求的问题-->
        <form id="form-for-360" method="post" :action="action" v-show="false">
            <input type="text" name="fileName" :value="filename"></input>
        </form>

        <el-button type="primary" size="mini" @click="read">read</el-button>
        <!--在线rade txt 文件-->
        <el-dialog title="《XXX隐私条款》" :visible.sync="privatePopShow" width="60%" align="center">
            <div class="agreement">
                <pre>{{encoderData}}</pre>
            </div>
            <span slot="footer" class="dialog-footer">
        <el-button @click="privatePopShow = false">关 闭</el-button>
    </span>
        </el-dialog>

    </div>
</template>

<script>

    import {showCapacity, showAllFile, showFileInfo} from '../api/FileManager'

    export default {
        name: "FileManager",
        data() {
            return {
                img: '../../../assets/blank.png',
                baseURL: '',
                path: _basePath,
                capacity: {},//系统容量信息
                status: {success: 'success', warning: 'warning', exception: 'exception'},
                fileList: [],
                pathArr: [],//维护了访问的历史记录
                backBtnVisitable: true,
                rightBtnVisitable: true,
                menuVisible: false,
                fileInfoVisible: false,
                fit: 'scale-down',
                currentItem: {},
                fileInfo: {},//文件详情
                channelId: '',
                websocket: null,
                filename: '',
                action: "http://" + _baseUrl + ":" + _basePort + "/api/file/downLoad",
                privatePopShow: false,
                txt:'',
                b64:"0M8R4KGxGuEAAAAAAAAAAAAAAAAAAAAAPgADAP7/CQAGAAAAAAAAAAAAAAABAAAAIAAAAAAAAAAAEAAAHwAAAAEAAAD+////AAAAACIAAAD////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////spcEAiogJBAAAFFC/AAAAAAAAEAAAAAAACAAAchgAAA4AS1NLU8MACAAAAAAAAAAAAAAAAAAAAAAAAAAECBYANCwAAAAAAAAAAAAAOQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//w8AAAAAAAAAAAD//w8AAAAAAAAAAAD//w8AAAAAAAAAAAAAAAAAAAAAAKQAAAAAADIFAAAAAAAAMgUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgwkAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMgUAACwAAABeBQAAJAAAAAAAAAAAAAAAlwUAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQgoAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARwkAACQAAADfBgAAaAIAAJcGAABIAAAAggUAABUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJcJAACrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGsJAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIADAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0ADQBEjZllJ1loUTZlMFIOVD1c61/dT1hb84FRf9h2DP8ylmJrq4iMVBCMMVlIZQ0ADQBil9WLmJiTXg0A/pSlYzoAaAB0AHQAcABzADoALwAvAHAAYQBuAC4AYgBhAGkAZAB1AC4AYwBvAG0ALwBzAC8AMQBlAFUAQQBQADcAQwA3ADIAegBQAFAAdgBmADMAUABqAGgAQgBJADgAbwBRAKAA0GPWUwF4OgA0ADUAdAA1AA0ADQBIAFQATQBMADUAKwBDAFMAUwAzAA0A/pSlYzoAaAB0AHQAcABzADoALwAvAHAAYQBuAC4AYgBhAGkAZAB1AC4AYwBvAG0ALwBzAC8AMQB5ADcAOQBjAGMASgBoAFkARABrAGUARABzAGsAcQBMAG8AZwBmADAAeQBnAKAA0GPWUwF4OgB4ADYANQAzAA0ADQB2AHUAZQAuAGoAcwDYmv9Of5mGTkhODQD+lKVjOgBoAHQAdABwAHMAOgAvAC8AcABhAG4ALgBiAGEAaQBkAHUALgBjAG8AbQAvAHMALwAxAEIAeQBaAGQAawBNAEsAOABvAGMAWgBjAE0AWgBTAE0AdwBiAEgAbABlAGcAoADQY9ZTAXg6ADMAMQA2ADcADQANAGEAbgBnAHUAbABhAHIAIABqAHMA/07JYv5SUX93AGUAYgANAP6UpWM6AGgAdAB0AHAAcwA6AC8ALwBwAGEAbgAuAGIAYQBpAGQAdQAuAGMAbwBtAC8AcwAvADEARgA3ADIAMwAwAF8ARAA4AEMAYwBJADcAegBOAEkARgBiAGsAVgBJAHAAUQCgANBj1lMBeDoANwBlAGUAaQANAA0AaIh9dl55aFYNAP6UpWM6AGgAdAB0AHAAcwA6AC8ALwBwAGEAbgAuAGIAYQBpAGQAdQAuAGMAbwBtAC8AcwAvADEAZgA3AGoAZABiADUAUgBLADMAcABaAFYARwBEAHIAbQA3AE4AVQBFAEMAQQCgANBj1lMBeDoAMAAxAGUAMAANAA0AcwBwAHIAaQBuAGcAYgBvAG8AdAABTxpOrl/hT7lwEJn7fN9+DQD+lKVjOgBoAHQAdABwAHMAOgAvAC8AcABhAG4ALgBiAGEAaQBkAHUALgBjAG8AbQAvAHMALwAxAG8AaQBiAHEAMgBaAC0ASQAxAEkAcABEAFUATgBQAHQATgBKAFIAQgA3AGcAoADQY9ZTAXg6AGMAMwB3ADEADQANAHYAdQBlACsAbgBvAGQAZQArAG0AbwBuAGcAbwBkAGIA2JqnfmhRCGgNAP6UpWM6AGgAdAB0AHAAcwA6AC8ALwBwAGEAbgAuAGIAYQBpAGQAdQAuAGMAbwBtAC8AcwAvADEAZQBfAEYAYQA5AFYAcwA5AFoAbQBtAFoATQBtAGMAbwBrAFEAXwBEAE0AdwCgANBj1lMBeDoAMwA2ADIAaAANAA0ATQB5AFMAUQBMAHBlbmOTXrZnhGcNAP6UpWM6AGgAdAB0AHAAcwA6AC8ALwBwAGEAbgAuAGIAYQBpAGQAdQAuAGMAbwBtAC8AcwAvADEANgBzAFcAZABrADkAUABNAGkASAAxAGYATgBQAFgARABwAHcAMABUAGUAdwCgANBj1lMBeDoAMwA5ADAAaQANAA0Arl/hTw9cC3qPXmVR6JUOTp5bGGINAP6UpWM6AGgAdAB0AHAAcwA6AC8ALwBwAGEAbgAuAGIAYQBpAGQAdQAuAGMAbwBtAC8AcwAvADEANQBuAFIAZgBCAFkAMgBWAGoASQBwAC0ATQB4AHcARQBQAGcAdABwADYAUQCgANBj1lMBeDoAMwA5ADEAZAANAA0AaABhAGQAbwBvAHAADQD+lKVjOgBoAHQAdABwAHMAOgAvAC8AcABhAG4ALgBiAGEAaQBkAHUALgBjAG8AbQAvAHMALwAxAGIAdABDAE0AOAB5AGcAOQAyAGoAOQBnAC0AZwA4AEYAbgB3AHEATQBoAGcAoADQY9ZTAXg6AHEAawAxAGsADQANAGMALQBjACsAKwANAP6UpWM6AGgAdAB0AHAAcwA6AC8ALwBwAGEAbgAuAGIAYQBpAGQAdQAuAGMAbwBtAC8AcwAvADEAUAA0AFoAMQAtAEwAdgBRAEwAegBEAHYATgB3AFQAcABmAFEAMABLADAAZwCgANBj1lMBeDoANAA1ADAAegANAA0ASgBTAGhRV1lZZQt6DQD+lKVjOgBoAHQAdABwAHMAOgAvAC8AcABhAG4ALgBiAGEAaQBkAHUALgBjAG8AbQAvAHMALwAxAEYAYQAzAEYAegBEAG8AOABLADUAaABUAEkAMQBUAFgATABIAC0ASQBpAEEAoADQY9ZTAXg6AHIAaABnAGwADQANAGIAbwBvAHQAcwB0AHIAYQBwAA0A/pSlYzoAaAB0AHQAcABzADoALwAvAHAAYQBuAC4AYgBhAGkAZAB1AC4AYwBvAG0ALwBzAC8AMQBVADUAMgBiAGIAdgBiADQAUQBRAGkAdwBpAHIAbgBvAHUATAB5AFAAZABnAKAA0GPWUwF4OgBmADMAMQB0AA0ADQBQAEgAUABoUcaWDQD+lKVjOgBoAHQAdABwAHMAOgAvAC8AcABhAG4ALgBiAGEAaQBkAHUALgBjAG8AbQAvAHMALwAxAE4ARwBsAHAAcgBtAFAALQAtADgAdwBnAEQASQBjAHQANgBVAGYARwB3AEEAoADQY9ZTAXg6ADkAMgB3AHEADQANAEMAIwANAP6UpWM6AGgAdAB0AHAAcwA6AC8ALwBwAGEAbgAuAGIAYQBpAGQAdQAuAGMAbwBtAC8AcwAvADEASwBsAFEASABLADIAdABlAE0AbAA4AGEAQQBYAE0ANwBnAEIAMwBGAGMAUQCgANBj1lMBeDoANwA3ADMANgANAA0AcABwAHQAaFFXWQ0A/pSlYzoAaAB0AHQAcABzADoALwAvAHAAYQBuAC4AYgBhAGkAZAB1AC4AYwBvAG0ALwBzAC8AMQBPAEQAWAB1AFoARwBkAHgAdgBJAGMAcwAzADEAagBRADUAXwBoAGwAeQB3AKAA0GPWUwF4OgA1ADEANAAxAA0ADQB2AHUAZQANAP6UpWM6AGgAdAB0AHAAcwA6AC8ALwBwAGEAbgAuAGIAYQBpAGQAdQAuAGMAbwBtAC8AcwAvADEAQgBTAGIAdwBZAGQAUQA2AGkAdgBwAEwARQBPADAASQA2AFkAQQB4AHgAZwCgANBj1lMBeDoAOQByADAANgANAA0AaQBPAFMADQD+lKVjOgBoAHQAdABwAHMAOgAvAC8AcABhAG4ALgBiAGEAaQBkAHUALgBjAG8AbQAvAHMALwAxAEMAQwBnADkAdQBNAGQARwA0AGMAdgAzADkAMABfAHQASABWAE0AWAB0AGcAoADQY9ZTAXg6ADAANAAzADEADQANAA0AbgBvAGQAZQAuAGoAcwBoUVdZDQD+lKVjOgBoAHQAdABwAHMAOgAvAC8AcABhAG4ALgBiAGEAaQBkAHUALgBjAG8AbQAvAHMALwAxAHIAVAA3AHoAUABDAEgAVgAwAEwANgBpAEYAZgBYAHoANAA2AEIAZwB6AEEAoADQY9ZTAXg6ADcAcgAxAHMADQANAGEAbgBnAHUAbABhAHIADQD+lKVjOgBoAHQAdABwAHMAOgAvAC8AcABhAG4ALgBiAGEAaQBkAHUALgBjAG8AbQAvAHMALwAxAEUANQBGAE8AQQBsAE0AdwBVAEUAMwBNADkARwBJAHYAVgBSAGcARwBiAEEAoADQY9ZTAXg6ADkAOAAxAHUADQANAEoAQQBWAEEADQD+lKVjOgBoAHQAdABwAHMAOgAvAC8AcABhAG4ALgBiAGEAaQBkAHUALgBjAG8AbQAvAHMALwAxAEoAYQBTAG4AaAA2AC0AQQBpAFcAYgA2AGYATQBuAC0AQgAtAGgAZAAtAGcAoADQY9ZTAXg6ADIAcgAzADAADQANAFcAZQBiAA0A/pSlYzoAaAB0AHQAcABzADoALwAvAHAAYQBuAC4AYgBhAGkAZAB1AC4AYwBvAG0ALwBzAC8AMQBEAEMAbQBHAFEARwBBAG4AYwAtAHoAcwBlAHkAdQBwAFYAMgBpAGgAUwB3AKAA0GPWUwF4OgA5AHIAaAA2AA0ADQANACdZcGVuYw0A/pSlYzoAaAB0AHQAcABzADoALwAvAHAAYQBuAC4AYgBhAGkAZAB1AC4AYwBvAG0ALwBzAC8AMQB0AE4AOABWAHoAUgA3AHAAQwBDAGUAeABPAGcAeAAtAHkAQgBpAHYAbgBnAKAA0GPWUwF4OgBuADEAZgA4AA0ADQBQAHkAdABoAG8AbgBoUVdZDQD+lKVjOgBoAHQAdABwAHMAOgAvAC8AcABhAG4ALgBiAGEAaQBkAHUALgBjAG8AbQAvAHMALwAxAEEANQBLAGEAUABTAEwAcwAyADcAUgA2AEoANQBCADkAMwAyAG0ARwBCAHcAoADQY9ZTAXg6AG4AbwAyAGUADQANADUAMAAwACxnNXVQW2ZODQD+lKVjOgBoAHQAdABwAHMAOgAvAC8AcABhAG4ALgBiAGEAaQBkAHUALgBjAG8AbQAvAHMALwAxAEwANAA0AG0AMABOAFIAcwBCAFAAeQBnAEIAYgBDAEYAZQAzAHUATABDAGcAoADQY9ZTAXg6ADcAdgA5AGEADQANAE8AcgBhAGMAbABlAA0A/pSlYzoAaAB0AHQAcABzADoALwAvAHAAYQBuAC4AYgBhAGkAZAB1AC4AYwBvAG0ALwBzAC8AMQByAGsAOABlAEcAVQBGAGMARQBZAHIAcQBhAHcAcAA0AEwAYQBfAEgAdgB3AKAA0GPWUwF4OgB1ADEAMgAxAA0ADQBhAHMAcAAuAG4AZQB0AA0A/pSlYzoAaAB0AHQAcABzADoALwAvAHAAYQBuAC4AYgBhAGkAZAB1AC4AYwBvAG0ALwBzAC8AMQBJAE0AQQBPAEUANAA1AFUAZAA5AHQAWgBmAGcAQQBmAGcAcgBYAGoAegB3AKAA0GPWUwF4OgBsAGgAZwBzAA0ADQBMiBpOgHuGUyFqf2cNAP6UpWM6AGgAdAB0AHAAcwA6AC8ALwBwAGEAbgAuAGIAYQBpAGQAdQAuAGMAbwBtAC8AcwAvADEAdwB6AFUAWgAxAFEAZwBkAGUATgB2AGgAbAA4AHoAWAB2AEUAegA3AC0AZwCgANBj1lMBeDoANwBjAGkAeAANAA0AgHuGUyFqf2cNAP6UpWM6AGgAdAB0AHAAcwA6AC8ALwBwAGEAbgAuAGIAYQBpAGQAdQAuAGMAbwBtAC8AcwAvADEASgBSAEUAZgBvADgAZQBWAFgALQBZADEAOQBsAHAATgAxAEwAdwBDAE0AdwCgANBj1lMBeDoAYgBkADAAdQANAA0ATABpAG4AdQB4AA0A/pSlYzoAaAB0AHQAcABzADoALwAvAHAAYQBuAC4AYgBhAGkAZAB1AC4AYwBvAG0ALwBzAC8AMQBpAG8AUgBpAFAAZABnAFAARABQADQATwB0ADUAUgBpAGIAdABwAE0AcgB3AKAA0GPWUwF4OgBhADcANQByAA0ADQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACCAAABAgAADAIAAAyCAAANAgAADwIAAA+CAAAtAgAALYIAAC4CAAAzAgAAM4IAABECQAARgkAAEgJAABeCQAAYAkAANYJAADYCQAA2gkAAPwJAAD+CQAAdAoAAHYKAAB4CgAAgAoAAIIKAAD4CgAA+goAAPwKAAAgCwAAIgsAAJgLAACaCwAAnAsAAMQLAADGCwAAPAwAAAAA+PMA7ejj3gDY087JAMO+ubQArqmknwCZlI+KAIR/enUAb2plAAAAAAAAAAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAAAAhtSAkEc0gJBAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAAAAhtSAkEc0gJBAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAAAAhtSAkEc0gJBAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAAAAhtSAkEc0gJBAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAAAAhtSAkEc0gJBAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAAAAhtSAkEc0gJBAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAAAAhtSAkEc0gJBAAIbUgJBHNICQQAAAAAAAAmPAwAAD4MAABADAAAVAwAAFYMAADMDAAAzgwAANAMAADkDAAA5gwAAFwNAABeDQAAYA0AAGwNAABuDQAA5A0AAOYNAADoDQAA8g0AAPQNAABqDgAAbA4AAG4OAAB6DgAAfA4AAPIOAAD0DgAA9g4AAAgPAAAKDwAAgA8AAIIPAACEDwAAjg8AAJAPAAAGEAAACBAAAAoQAAAOEAAA+gD07+rlAN/a1dAAysXAuwC1sKumAKCblpEAi4aBfAB2cWxnAGEIbUgJBHNICQQAAAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAIbUgJBHNICQQAAAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAIbUgJBHNICQQAAAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAIbUgJBHNICQQAAAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAIbUgJBHNICQQAAAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAIbUgJBHNICQQAAAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAIbUgJBHNICQQAAAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAIbUgJBHNICQQAAAAIbUgJBHNICQQAACYOEAAAEBAAAIYQAACIEAAAihAAAJQQAACWEAAADBEAAA4RAAAQEQAAFhEAABgRAACOEQAAkBEAAJIRAACYEQAAmhEAABASAAASEgAAFBIAABYSAAAoEgAAKhIAAKASAACiEgAApBIAALISAAC0EgAAKhMAACwTAAAuEwAANhMAADgTAACuEwAAsBMAALITAAC4EwAAuhMAADAUAAD69fAA6uXg2wDV0MvGAMC7trEAAKqloJsAlZCLhgCAe3ZxAGtmYQhtSAkEc0gJBAAIbUgJBHNICQQACG1ICQRzSAkEAAAACG1ICQRzSAkEAAhtSAkEc0gJBAAIbUgJBHNICQQACG1ICQRzSAkEAAAACG1ICQRzSAkEAAhtSAkEc0gJBAAIbUgJBHNICQQACG1ICQRzSAkEAAAACG1ICQRzSAkEAAhtSAkEc0gJBAAIbUgJBHNICQQACG1ICQRzSAkEAAAAAAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAIbUgJBHNICQQAAAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAIbUgJBHNICQQAAAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAIbUgJBHNICQQAAAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAAJjAUAAAyFAAANBQAADYUAAA8FAAAPhQAALQUAAC2FAAAuBQAAMgUAADKFAAAQBUAAEIVAABEFQAAUhUAAFQVAADKFQAAzBUAAM4VAADaFQAA3BUAAFIWAABUFgAAVhYAAGQWAABmFgAA3BYAAN4WAADgFgAA7BYAAO4WAABkFwAAZhcAAGgXAABwFwAAchcAAOgXAADqFwAA7BcAAPoAAPPu6eQA3tnUzwDJxL+6ALSvqqUAn5qVkACKhYB7AHVwa2YAAAAAAAAAAAAAAAhtSAkEc0gJBAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAAAAhtSAkEc0gJBAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAAAAhtSAkEc0gJBAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAAAAhtSAkEc0gJBAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAAAAhtSAkEc0gJBAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAAAAhtSAkEc0gJBAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAAAAhtSAkEc0gJBAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAAAAAACG1ICQRzSAkEAAAm7BcAAPYXAAD4FwAAbhgAAHAYAAByGAAA+vXw6wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIbUgJBHNICQQACG1ICQRzSAkEAAhtSAkEc0gJBAAIbUgJBHNICQQAAAUACAAAAggAAAQIAAAyCAAANAgAAD4IAAC2CAAAuAgAAM4IAABGCQAASAkAAGAJAADYCQAA2gkAAP4JAAB2CgAAeAoAAIIKAAD6CgAA/AoAACILAACaCwAAnAsAAMYLAAA+DAAA/QAAAAAAAAAAAAAAAPsAAAAAAAAAAAAAAAD5AAAAAAAAAAAAAAAA9wAAAAAAAAAAAAAAAPUAAAAAAAAAAAAAAADzAAAAAAAAAAAAAAAA8QAAAAAAAAAAAAAAAO8AAAAAAAAAAAAAAADtAAAAAAAAAAAAAAAA6wAAAAAAAAAAAAAAAOkAAAAAAAAAAAAAAADnAAAAAAAAAAAAAAAA5QAAAAAAAAAAAAAAAOMAAAAAAAAAAAAAAADhAAAAAAAAAAAAAAAA3wAAAAAAAAAAAAAAAN0AAAAAAAAAAAAAAADbAAAAAAAAAAAAAAAA2QAAAAAAAAAAAAAAANcAAAAAAAAAAAAAAADVAAAAAAAAAAAAAAAA0wAAAAAAAAAAAAAAANEAAAAAAAAAAAAAAADPAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAGD4MAABADAAAVgwAAM4MAADQDAAA5gwAAF4NAABgDQAAbg0AAOYNAADoDQAA9A0AAGwOAABuDgAAfA4AAPQOAAD2DgAACg8AAIIPAACEDwAAkA8AAAgQAAAKEAAAEBAAAIgQAAD9AAAAAAAAAAAAAAAA+wAAAAAAAAAAAAAAAPkAAAAAAAAAAAAAAAD3AAAAAAAAAAAAAAAA9QAAAAAAAAAAAAAAAPMAAAAAAAAAAAAAAADxAAAAAAAAAAAAAAAA7wAAAAAAAAAAAAAAAO0AAAAAAAAAAAAAAADrAAAAAAAAAAAAAAAA6QAAAAAAAAAAAAAAAOcAAAAAAAAAAAAAAADlAAAAAAAAAAAAAAAA4wAAAAAAAAAAAAAAAOEAAAAAAAAAAAAAAADfAAAAAAAAAAAAAAAA3QAAAAAAAAAAAAAAANsAAAAAAAAAAAAAAADZAAAAAAAAAAAAAAAA1wAAAAAAAAAAAAAAANUAAAAAAAAAAAAAAADTAAAAAAAAAAAAAAAA0QAAAAAAAAAAAAAAAM8AAAAAAAAAAAAAAAAAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAAYiBAAAIoQAACWEAAADhEAABARAAAYEQAAkBEAAJIRAACaEQAAEhIAABQSAAAWEgAAKhIAAKISAACkEgAAtBIAACwTAAAuEwAAOBMAALATAACyEwAAuhMAADIUAAA0FAAANhQAAP0AAAAAAAAAAAAAAAD7AAAAAAAAAAAAAAAA+QAAAAAAAAAAAAAAAPcAAAAAAAAAAAAAAAD1AAAAAAAAAAAAAAAA8wAAAAAAAAAAAAAAAPEAAAAAAAAAAAAAAADvAAAAAAAAAAAAAAAA7QAAAAAAAAAAAAAAAOsAAAAAAAAAAAAAAADpAAAAAAAAAAAAAAAA5wAAAAAAAAAAAAAAAOUAAAAAAAAAAAAAAADjAAAAAAAAAAAAAAAA4QAAAAAAAAAAAAAAAN8AAAAAAAAAAAAAAADdAAAAAAAAAAAAAAAA2wAAAAAAAAAAAAAAANkAAAAAAAAAAAAAAADXAAAAAAAAAAAAAAAA1QAAAAAAAAAAAAAAANMAAAAAAAAAAAAAAADRAAAAAAAAAAAAAAAAzwAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAABg2FAAAPhQAALYUAAC4FAAAyhQAAEIVAABEFQAAVBUAAMwVAADOFQAA3BUAAFQWAABWFgAAZhYAAN4WAADgFgAA7hYAAGYXAABoFwAAchcAAOoXAADsFwAA+BcAAHAYAAByGAAA/QAAAAAAAAAAAAAAAPsAAAAAAAAAAAAAAAD5AAAAAAAAAAAAAAAA9wAAAAAAAAAAAAAAAPUAAAAAAAAAAAAAAADzAAAAAAAAAAAAAAAA8QAAAAAAAAAAAAAAAO8AAAAAAAAAAAAAAADtAAAAAAAAAAAAAAAA6wAAAAAAAAAAAAAAAOkAAAAAAAAAAAAAAADnAAAAAAAAAAAAAAAA5QAAAAAAAAAAAAAAAOMAAAAAAAAAAAAAAADhAAAAAAAAAAAAAAAA3wAAAAAAAAAAAAAAAN0AAAAAAAAAAAAAAADbAAAAAAAAAAAAAAAA2QAAAAAAAAAAAAAAANcAAAAAAAAAAAAAAADVAAAAAAAAAAAAAAAA0wAAAAAAAAAAAAAAANEAAAAAAAAAAAAAAADPAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAGDIAH7CCLiCwxkEhsAgHI5CgBSKwCAckkKAFJbAAACoyABewUwMYsOADMlACADGQOAEdMAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJgQPABIAAQAEAQ8ABAACAAEAAgAAAAQAAAAAAAgAAAAOAAAADgAAAA4AAAAOAAAADgAAAA4AAAAOAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAgAAAAAAAAAAAAAAAAAAAA2BgAANgYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2BgAANgYAADYGAAA2BgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANgYAADYGAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAADYGAAA2BgAANgYAADYGAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAABaAABA8f8CAFoAAAAAAAAAAAAAAAIAY2uHZQAACwAAAGEkAwMkAzEkAAAwAENKFQBPSgIAUEoBAFFKAgBeSgMAYUoWAEtIAgBtSAkEc0gJBG5IBAh0SAQIX0gBBAAAAAAAAAAAAAAAAAAAAAAAADQAQUDy/6EANAAAAAAAAAAAAAAABgDYnqSLtWs9hFdbU08AABAAT0oCAFBKAQBRSgIAXkoDAF4AaUDz/7MAXgAAAAAAAAAAAAAABABuZhqQaIg8aAAAKAA6VgsANNYGAAEBAwAANNYGAAECA2wANNYGAAEEAwAANNYGAAEIA2wAAgALABAAT0oCAFBKAQBRSgIAXkoDAAAAAAAAAAAIAAA8DAAADhAAADAUAADsFwAAchgAAA0AAAAOAAAADwAAABAAAAARAAAAAAgAAD4MAACIEAAANhQAAHIYAAASAAAAEwAAABQAAAAVAAAAAhAAAAAAAAAAOQgAAAAAAAgAAAAABAAAAEcWkAEAAAICBgMFBAUCAwSHegAgAAAAgAgAAAAAAAAA/wEAAAAAAABUAGkAbQBlAHMAIABOAGUAdwAgAFIAbwBtAGEAbgAAADsEkAGGAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACLW1NPAABTAGkAbQBTAHUAbgAAADckkAEAAAIPBQICAgQDAgQAAAAAAAAAAAEAAAAAAAAAnwEAAAAAAABDAGEAbABpAGIAcgBpAAAAPySQAQAGAgsGBAICAgICBP8qAOBDeADACQAAAAAAAAD/AQBAAAD//0EAcgBpAGEAbAAAAEEAcgBpAGEAbAAAAP//EgAAAAAAAAAAAAAAAAAAAAkAUABSAEEALQBBAEwAMAAwAFgABgBpAFAAaABvAG4AZQAAAAAAAAAAAAAAAAAAAAAAAAAAACAABAABCIgYAACkAQAAaAEAAAAABaN8p6WjfKcAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAEAAOAAAAAAAAAAAAAAAAAAQABAAAAAQAAAAAAAAABgAAAAAAAAAMAfgA2ACEAJQApACwALgA6ADsAPgA/AF0AfQCiAKgAsAC3AMcCyQIVIBYgGSAdICYgMCAyIDMgOiADITYiATACMAMwCTALMA0wDzARMBUwFzAeMDb+Ov4+/kD+RP5a/lz+Xv4B/wL/Bf8H/wn/DP8O/xr/G/8f/z3/QP9c/13/Xv/g/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkACgAWwB7AKMApQC3ABggHCAIMAowDDAOMBAwFDAWMB0wWf5b/l3+BP8I/w7/O/9b/+H/5f8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIB6AFtACcAAKAEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8/QEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKfD/DwEAAT8AAKgDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJyoXAAAAAAAyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAgAAADlAAAAAAAAAAAAAAAAAAAAOQgAAAAAACwAAAAA/////w8AAPAgAAAAAAAG8BgAAAACCAAAAgAAAAIAAAABAAAAAQAAAAIAAAAADwAC8HoAAAAQAAjwCAAAAAIAAAABBAAADwAD8DAAAAAPAATwKAAAAAEACfAQAAAAAAAAAAAAAAAAAAAAAAAAAAIACvAIAAAAAAAAAAUAAAAPAATwKgAAABIACvAIAAAAAQQAAAAOAAAzAAvwEgAAAL8BAQARAP8BAAAIAD8DAQABAP9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v8AAAYBAgAAAAAAAAAAAAAAAAAAAAAAAQAAAOCFn/L5T2gQq5EIACsns9kwAAAAdAEAABEAAAABAAAAkAAAAAIAAACYAAAAAwAAAKQAAAAEAAAAsAAAAAUAAADMAAAABgAAANgAAAAHAAAA5AAAAAgAAADwAAAACQAAAAgBAAAMAAAAFAEAAA0AAAAgAQAADgAAACwBAAAPAAAANAEAABAAAAA8AQAAEgAAAEQBAAATAAAAZAEAAAAAAIBsAQAAAgAAALAEAAAfAAAAAQAAAAAAAAAfAAAAAQAAAAAAAAAfAAAACgAAAFAAUgBBAC0AQQBMADAAMABYAAAAHwAAAAEAAAAAAAAAHwAAAAEAAAAAAAAAHwAAAAEAAAAAAAAAHwAAAAcAAABpAFAAaABvAG4AZQAAAAAAHwAAAAEAAAAAAAAAQAAAAIByxMDqttUBQAAAAACcCun/ttUBAwAAAAAAAAADAAAAAAAAAAMAAAAAAAAAHwAAAAsAAABXAFAAUwAgAE8AZgBmAGkAYwBlAAAAAAADAAAAAAAAABMAAAAECAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7/AAAGAQIAAAAAAAAAAAAAAAAAAAAAAAIAAAAC1c3VnC4bEJOXCAArLPmuRAAAAAXVzdWcLhsQk5cIACss+a5YAQAAFAEAABAAAAABAAAAiAAAAAIAAACQAAAAAwAAAJwAAAAEAAAAqAAAAAUAAACwAAAABgAAALgAAAAHAAAAwAAAAAgAAADIAAAACQAAANAAAAAKAAAA2AAAAAsAAADgAAAADgAAAOYAAAAPAAAA8gAAABAAAAD+AAAAEQAAAAQBAAAAAACADAEAAAIAAACwBAAAHwAAAAEAAAAAAAAAHwAAAAEAAAAAAAAAAwAAAAAAAAADAAAAAAAAAAMAAAAAAAAAAwAAAAAAAAADAAAAAAAAAAMAAAAAAAAAAwAAAAAAAAALAAAAAAAfAAAAAQAAAAAAAAAfAAAAAQAAAAAAAAALAAAAAAADAAAAAAAAABMAAAAECAAAjAAAAAQAAAAAAAAAKAAAAAEAAABcAAAAAgAAAGQAAAAAAACAhAAAAAEAAAACAAAAEwAAAEsAUwBPAFAAcgBvAGQAdQBjAHQAQgB1AGkAbABkAFYAZQByAAAAAAACAAAAsAQAAB8AAAAMAAAAMgAwADUAMgAtADEAMAAuADIALgAwAAAAEwAAAAQIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAACAAAAAwAAAAQAAAAFAAAABgAAAAcAAAAIAAAACQAAAAoAAAALAAAADAAAAA0AAAAOAAAADwAAABAAAAARAAAAEgAAABMAAAAUAAAAFQAAABYAAAAXAAAAGAAAABkAAAAaAAAAGwAAABwAAAAdAAAAHgAAAB8AAAAgAAAAIQAAACIAAAAjAAAAJAAAACUAAAAmAAAAJwAAACgAAAApAAAA/v///ysAAAAsAAAALQAAAC4AAAAvAAAAMAAAAP7///8yAAAAMwAAADQAAAA1AAAANgAAADcAAAA4AAAA/v//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////UgBvAG8AdAAgAEUAbgB0AHIAeQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYABQD//////////wIAAAAGCQIAAAAAAMAAAAAAAABGAAAAAAAAAAAAAAAAAAAAAAAAAAAXAAAAQA4AAAAAAABXAG8AcgBkAEQAbwBjAHUAbQBlAG4AdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGgACAP///////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0LAAAAAAAADAAVABhAGIAbABlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAIBAwAAAAQAAAD/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEQKAAAAAAAARABhAHQAYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAgH///////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+////AAAAAAAAAAAFAFMAdQBtAG0AYQByAHkASQBuAGYAbwByAG0AYQB0AGkAbwBuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAACAQEAAAAFAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACoAAACkAQAAAAAAAAUARABvAGMAdQBtAGUAbgB0AFMAdQBtAG0AYQByAHkASQBuAGYAbwByAG0AYQB0AGkAbwBuAAAAAAAAAAAAAAA4AAIA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMQAAAOQBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAACAAAAAwAAAAQAAAAFAAAABgAAAAcAAAAIAAAACQAAAAoAAAALAAAADAAAAA0AAAAOAAAADwAAABAAAAARAAAAEgAAABMAAAAUAAAAFQAAABYAAAD+////GAAAABkAAAAaAAAAGwAAABwAAAAdAAAAHgAAAP7////+////IQAAAP7////9////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////",
                encoderData:'',
            }
        },
        created() {
            this.pathArr.push(this.path);
            this.getCapacity();
            this.getFileList();
            this.initWebSocket();
        },
        destroyed() {
            this.websocket.close() //离开路由之后断开websocket连接
        },
        methods: {
            getCapacity() {
                let param = {path: this.path};
                showCapacity(param).then((result) => {
                    let data = result.data;
                    if (data.success == "true") {
                        this.capacity = data.data;
                    } else {
                        this.$message({type: 'error', message: '获取系统信息失败！'})
                    }
                })
            },
            getFileList() {
                let loading = showLoad(this);
                let param = {path: this.path};
                showAllFile(param).then((result) => {
                    let data = result.data;
                    if (data.success == "true") {
                        this.fileList = data.data;
                    } else {
                        this.$message({type: 'error', message: '获取文件列表失败！'})
                    }
                    loading.close();
                })

            },
            openFile(item) {
                console.log("双击");
                if (item.isDirectory == "directory") {//是目录
                    this.path = item.path;
                    this.pathArr.push(this.path);
                    this.getFileList();
                } else {

                }

            },
            //后退
            handlerBackBtn() {
                //获取当前path在数组中的index
                let index = this.pathArr.indexOf(this.path);
                if (index != -1) {
                    //得到前一个元素
                    this.path = this.pathArr[index - 1];
                    this.getFileList();
                }

            },
            //前进
            handlerRightBtn() {
                //获取当前path在数组中的index
                let index = this.pathArr.indexOf(this.path);
                if (index != -1) {
                    //得到前一个元素
                    this.path = this.pathArr[index + 1];
                    this.getFileList();
                }
            },
            /*下载文件*/
            downLoadFile() {
                this.filename = this.currentItem.path;
                const a = document.createElement('A');//创建a标签
                a.setAttribute('href', '#');
                a.setAttribute('onclick', this.formDownload() + ';return false;');
                a.click();

            },
            formDownload() {
                document.getElementById("form-for-360").submit();
            },
            //刷新
            handlerRefreshBtn() {
                this.getFileList();

            },
            //右击
            rightClick(item, event) { // 鼠标右击触发事件
                this.currentItem = item;
                this.menuVisible = false // 先把模态框关死，目的是 第二次或者第n次右键鼠标的时候 它默认的是true
                this.menuVisible = true  // 显示模态窗口，跳出自定义菜单栏
                let menu = document.querySelector('#menu')
                //menu.style.left = event.clientX - 160 + 'px'
                menu.style.left = event.clientX + 'px';
                document.addEventListener('click', this.foo) // 给整个document添加监听鼠标事件，点击任何位置执行foo方法
                //menu.style.top = event.clientY - 10 + 'px'
                menu.style.top = event.clientY + 'px';
            },
            foo() { // 取消鼠标监听事件 菜单栏
                this.menuVisible = false
                document.removeEventListener('click', this.foo) // 要及时关掉监听，不关掉的是一个坑，不信你试试，虽然前台显示的时候没有啥毛病，加一个alert你就知道了
            },
            //鼠标移入
            mouseOver(item, event) {
                let currentTarget = event.currentTarget;
                currentTarget.style.cssText += 'background-color: rgba(64,158,255,0.3);'
            },
            //鼠标移出
            mouseLeave(item, event) {
                let currentTarget = event.currentTarget;
                currentTarget.style.cssText -= 'background-color:rgba(64,158,255,0.3);'
            },
            //getFileInfo查看文件详细信息
            getFileInfo() {
                this.fileInfoVisible = true;
                let param = {path: this.currentItem.path, channelId: this.channelId};
                showFileInfo(param).then((result) => {
                    this.fileInfo = result.data.data;

                })
            },
            handleFileInfoClose() {
                this.fileInfoVisible = false;
            },
            read(){
                this.privatePopShow = true;
                this.encoderData = _base64.decode(this.b64);
                //this.txt = this.readTxtFile();
            },
            //读取文本文件
            readTxtFile() {
                // 创建一个新的xhr对象
                let xhr = null;
                let okStatus = document.location.protocol === 'file' ? 0 : 200;
                xhr = window.XMLHttpRequest ? new XMLHttpRequest() : new ActiveXObject('Microsoft.XMLHTTP')
                xhr.open('GET', "/D:/新建文本文档.txt", false)
                xhr.overrideMimeType('text/html;charset=utf-8')
                xhr.send(null);
                return xhr.status === okStatus ? xhr.responseText : null
            },

            //********************************
            initWebSocket() { //初始化weosocket
                this.websocket = new WebSocket("ws://" + _baseUrl + ":" + _wsPort + "/getFileSize");
                this.websocket.onmessage = this.websocketonmessage;
                this.websocket.onopen = this.websocketonopen;
                this.websocket.onerror = this.websocketonerror;
                this.websocket.onclose = this.websocketclose;
            },
            websocketonopen() { //连接建立之后执行send方法发送数据
                let param = {userId: "A0001"};
                this.websocketsend(param);

            },
            websocketonerror() {//连接建立失败重连

                this.initWebSocket();
            },
            websocketonmessage(e) {
                console.log(e);
                let data = JSON.parse(e.data);
                console.log("data", data);
                switch (data.action) {
                    case 1://第一次连接或者重连
                        this.channelId = data.chatMsg.msg;
                        break;
                    case 2:
                        this.fileInfo.size = data.chatMsg.msg;
                        console.log("this.fileInfo", this.fileInfo);
                        break;
                }


            },
            websocketsend(data) {//数据发送
                let json = JSON.stringify(data);
                this.websocket.send(json);
            },
            websocketclose(e) {  //关闭
                console.log('断开连接', e);
            },
        },

        watch: {
            path() {
                //如果当前数组元素大于1
                if (this.pathArr.length > 1) {
                    //如果当前path处于arr的0index，则不可以后退
                    if (this.pathArr.indexOf(this.path) == 0 && this.pathArr.indexOf(this.path) != -1) {
                        this.backBtnVisitable = true;
                    } else {
                        this.backBtnVisitable = false;
                    }
                    //如果当前path处于arr的last index，则不可以前进
                    if (this.pathArr.indexOf(this.path) == this.pathArr.length - 1 && this.pathArr.indexOf(this.path) != -1) {
                        this.rightBtnVisitable = true;
                    } else {
                        this.rightBtnVisitable = false;
                    }

                } else {
                    this.backBtnVisitable = true;
                    this.rightBtnVisitable = true;
                }

            }
        },
        filters: {
            statusFilter(val) {
                if (val > 60) {
                    return "success";
                } else if (val > 20) {
                    return "warning";
                } else {
                    return "exception";
                }
            },
            capacityFilter(val) {
                let data = val / 1000 / 1000;

                if (data >= 1000) {
                    return (data / 1000).toFixed(1).toString() + " GB";
                } else {
                    return data.toFixed(0).toString() + " MB";
                }
            }
        }
    }
</script>

<style scoped>
    .icon-div {
        float: left;
        margin: 5px 5px 0 5px;
        cursor: pointer;
        /*overflow: hidden;*/
    }

    .div-img {
        margin-top: 15px;
    }

    .img-div-p {

        /*width: 60px;*/
        /*overflow: hidden;*/
        /*text-overflow:ellipsis;*/
        /*white-space: nowrap;*/
        width: 120px;
        height: 20px;
        display: inline-block;
        overflow: hidden; /* 超出的文本隐藏 */
        text-overflow: ellipsis; /* 溢出用省略号显示 */
        display: -webkit-box; /* 将对象作为弹性伸缩盒子模型显示 */
        -webkit-box-orient: vertical; /* 这个属性不是css的规范属性，需要组合上面两个属性，表示显示的行数 */
        -webkit-line-clamp: 1; /*  从上到下垂直排列子元素（设置伸缩盒子的子元素排列方式） */
    }

    .img-div-p:hover {
        text-overflow: ellipsis;
        white-space: nowrap;

    }

    .menu__item {
        display: block;
        line-height: 20px;
        text-align: left;
        margin-top: 10px;


    }

    .menu__item_line {
        margin: 0px;
        padding: 0px;
        font-size: 0px;
        height: 1px;
        overflow: hidden;
        background: #d7d7d7;
    }

    .menu {
        width: 70px;
        position: absolute;
        border-radius: 4px;
        border: 1px solid #999999;
        background-color: #f4f4f4;
    }

    li:hover {
        background-color: #1790ff;
        color: white;
    }

    .el-p {
        margin: 5px 0 5px 0;
        text-align: left;
    }

    .agreement {
        text-align: left;
        line-height: 25px;
        white-space: pre-line; /* pre-line、pre-wrap 也可以 */
        font-family: Avenir, Helvetica, Arial, sans-serif;

    }

</style>